# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pathrunner < Formula
  desc "AWS post-exploitation framework for automating privilege escalation paths"
  homepage "https://github.com/DataDog/pathrunner"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/pathrunner/releases/download/v0.2.3/pathrunner_0.2.3_darwin_amd64.tar.gz"
      sha256 "c679831418ddb02c3898eed6e287df32ed46f281b44cb5264e15e196320eb198"

      define_method(:install) do
        bin.install "pathrunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/pathrunner/releases/download/v0.2.3/pathrunner_0.2.3_darwin_arm64.tar.gz"
      sha256 "bf5870f609889379adf46b96e99572ebe372c189395483fef544117ea92ef930"

      define_method(:install) do
        bin.install "pathrunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/pathrunner/releases/download/v0.2.3/pathrunner_0.2.3_linux_amd64.tar.gz"
      sha256 "b7a53c11562047aa30486c7686c49b45d1a797d6f2f04416dff3b731d6cc048f"
      define_method(:install) do
        bin.install "pathrunner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/pathrunner/releases/download/v0.2.3/pathrunner_0.2.3_linux_arm64.tar.gz"
      sha256 "17b91ab1b0932566c2efb3dce85ae5ae5fe1a2a2fe45808a2ceda0131d39eb00"
      define_method(:install) do
        bin.install "pathrunner"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pathrunner version")
  end
end
