# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pathrunner < Formula
  desc "AWS post-exploitation framework for automating privilege escalation paths"
  homepage "https://github.com/DataDog/pathrunner"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/pathrunner/releases/download/v0.2.1/pathrunner_0.2.1_darwin_amd64.tar.gz"
      sha256 "44755d0291d9b22f0ddc2e1cd93e33bad842b331374640560c21ae69552ae149"

      define_method(:install) do
        bin.install "pathrunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/pathrunner/releases/download/v0.2.1/pathrunner_0.2.1_darwin_arm64.tar.gz"
      sha256 "716e9461818129f00af95d3fc16c8bd56f68c9e155702781ee7d94130507ff10"

      define_method(:install) do
        bin.install "pathrunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/pathrunner/releases/download/v0.2.1/pathrunner_0.2.1_linux_amd64.tar.gz"
      sha256 "98dc5fbd0d0109f1a4bbf91a0229bd7e43e90490c9052effa2b49f94c0bedb28"
      define_method(:install) do
        bin.install "pathrunner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/pathrunner/releases/download/v0.2.1/pathrunner_0.2.1_linux_arm64.tar.gz"
      sha256 "9ec1379eb8fce85524f306471cdf221b2fd4e0f330dfdad445ea1981cdd7f5f0"
      define_method(:install) do
        bin.install "pathrunner"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pathrunner version")
  end
end
