//go:build ignore

// gen_register.go generates register.go files that contain blank imports for
// auto-registering exploit modules and payload packages. Run via go generate.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

const registerTemplate = `// Code generated by scripts/gen_register.go; DO NOT EDIT.

package {{ .Package }}

import (
{{- range .Imports }}
	_ "{{ . }}"
{{- end }}
)
`

func main() {
	if len(os.Args) < 4 {
		fmt.Fprintf(os.Stderr, "usage: gen_register <package> <scan-dir> <output-file>\n")
		os.Exit(1)
	}

	packageName := os.Args[1]
	scanDir := os.Args[2]
	outputFile := os.Args[3]

	entries, err := os.ReadDir(scanDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read directory %s: %v\n", scanDir, err)
		os.Exit(1)
	}

	// Get the module path from go.mod to build import paths
	modulePath := getModulePath()

	// Resolve scanDir to absolute path, then compute its Go import path
	// by finding it relative to the module root (where go.mod lives)
	absScanDir, err := filepath.Abs(scanDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to resolve %s: %v\n", scanDir, err)
		os.Exit(1)
	}

	// Find the module root (directory containing go.mod)
	moduleRoot := filepath.Dir(findGoMod())

	var imports []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		dirPath := filepath.Join(absScanDir, entry.Name())
		if !containsGoFiles(dirPath) {
			continue
		}
		if entry.Name() == "shared" {
			continue
		}

		relPath, err := filepath.Rel(moduleRoot, dirPath)
		if err != nil {
			continue
		}
		importPath := modulePath + "/" + filepath.ToSlash(relPath)
		imports = append(imports, importPath)
	}

	sort.Strings(imports)

	tmpl := template.Must(template.New("register").Parse(registerTemplate))

	f, err := os.Create(outputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to create %s: %v\n", outputFile, err)
		os.Exit(1)
	}
	defer f.Close()

	data := struct {
		Package string
		Imports []string
	}{
		Package: packageName,
		Imports: imports,
	}

	if err := tmpl.Execute(f, data); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s with %d imports\n", outputFile, len(imports))
}

func findGoMod() string {
	dir, _ := os.Getwd()
	for {
		candidate := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	fmt.Fprintf(os.Stderr, "could not find go.mod in any parent directory\n")
	os.Exit(1)
	return ""
}

func getModulePath() string {
	data, err := os.ReadFile(findGoMod())
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read go.mod: %v\n", err)
		os.Exit(1)
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	fmt.Fprintf(os.Stderr, "could not find module path in go.mod\n")
	os.Exit(1)
	return ""
}

func containsGoFiles(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") && !strings.HasSuffix(e.Name(), "_test.go") {
			return true
		}
	}
	return false
}
